#!/bin/bash

PROGRAM=$1
NAME=$2
EXT=$3


for file in $(ls ./ | grep $NAME | grep $EXT)
do
    cat $file | ./$PROGRAM > /tmp/out
    diff -q /tmp/out $(echo "${file%%.*}".cor) &>/dev/null
    if [ $? -eq 0 ]
    then
        echo "OK $file"
    else 
        echo "FAIL $file"
	echo "############"
	echo "Expected: "
        cat $(echo "${file%%.*}".cor)
	echo "------------------"
	echo "Result: "
        cat /tmp/out
	echo "------------------"
	echo "############"
	echo ""
    fi
done
