#!/bin/bash

if [ $# -ne 3 ]
then
    echo "Usage: $0  <PROGRAM> <INPUT EXTENSION> <OUTPUT EXTENSION>"
    exit 1
fi

PROGRAM=$1
EXTINP=$2
EXTCHECK=$3


for file in $(ls ./ |  grep $EXTINP)
do
    cat $file | ./$PROGRAM > /tmp/out
    diff -q /tmp/out $(echo "${file%%.*}".$EXTCHECK) &>/dev/null
    if [ $? -eq 0 ]
    then
        echo "OK $file"
    else 
        echo "FAIL $file"
	echo "############"
	echo "Expected: "
        cat $(echo "${file%%.*}".$EXTCHECK)
	echo "------------------"
	echo "Result: "
        cat /tmp/out
	echo "------------------"
	echo "############"
	echo ""
    fi
done
